# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="Example.mp3"
Content-Type: audio/mpeg

< ./Example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/5ac910a4-4738-4c24-8992-018b0861bbad/transcription
Content-Type: application/json

{
  "prompt": "reflexão, vida, conhecimento"
}